using System;
using System.IO;
using DiceHero;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

/// <summary>Editor utilities: scene + player setup, builds, preview renders and batch playtests (usable from batch mode).</summary>
public static class DiceHeroSetup
{
    const string ScenePath = "Assets/Scenes/Main.unity";
    const string BaseMatPath = "Assets/Materials/Base.mat";
    public const string Version = "2.0.0";

    [MenuItem("Roll Power/Rebuild Main Scene")]
    public static void Setup()
    {
        ConfigurePlayer();
        UrpSetup.Configure();

        Directory.CreateDirectory("Assets/Materials");
        Directory.CreateDirectory("Assets/Scenes");
        var lit = Shader.Find("Universal Render Pipeline/Lit");
        var baseMat = AssetDatabase.LoadAssetAtPath<Material>(BaseMatPath);
        if (baseMat == null || baseMat.shader != lit)
        {
            if (baseMat != null) AssetDatabase.DeleteAsset(BaseMatPath);
            baseMat = new Material(lit) { name = "Base" };
            AssetDatabase.CreateAsset(baseMat, BaseMatPath);
        }

        const string glowPath = "Assets/Materials/Glow.mat";
        var glowMat = AssetDatabase.LoadAssetAtPath<Material>(glowPath);
        if (glowMat == null || glowMat.shader != lit)
        {
            if (glowMat != null) AssetDatabase.DeleteAsset(glowPath);
            glowMat = new Material(lit) { name = "Glow" };
            glowMat.EnableKeyword("_EMISSION");
            glowMat.SetColor("_EmissionColor", Color.cyan * 2f);
            glowMat.globalIlluminationFlags = MaterialGlobalIlluminationFlags.RealtimeEmissive;
            AssetDatabase.CreateAsset(glowMat, glowPath);
        }

        var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

        var camGo = new GameObject("Main Camera") { tag = "MainCamera" };
        var cam = camGo.AddComponent<Camera>();
        cam.fieldOfView = 40f;
        cam.nearClipPlane = 0.3f;
        cam.farClipPlane = 250f;
        cam.clearFlags = CameraClearFlags.SolidColor;
        cam.backgroundColor = World.SpaceColor;
        camGo.AddComponent<AudioListener>();
        camGo.AddComponent<CameraFollow>();
        UrpSetup.AddToScene(cam);

        var sunGo = new GameObject("Sun");
        var sun = sunGo.AddComponent<Light>();
        sun.type = LightType.Directional;

        var game = new GameObject("Game");
        var boot = game.AddComponent<GameBootstrap>();
        boot.baseMaterial = baseMat;
        boot.glowMaterial = glowMat;

        EditorSceneManager.SaveScene(scene, ScenePath);
        EditorBuildSettings.scenes = new[] { new EditorBuildSettingsScene(ScenePath, true) };
        AssetDatabase.SaveAssets();
        Debug.Log("[RollPower] Main scene created at " + ScenePath);
    }

    /// <summary>Product identity, input axes and platform settings (safe to run repeatedly).</summary>
    [MenuItem("Roll Power/Configure Player Settings")]
    public static void ConfigurePlayer()
    {
        PlayerSettings.colorSpace = ColorSpace.Linear;
        PlayerSettings.productName = "Roll Power";
        PlayerSettings.companyName = "ZizmanTK";
        PlayerSettings.bundleVersion = Version;
        PlayerSettings.SetApplicationIdentifier(UnityEditor.Build.NamedBuildTarget.Standalone, "com.zizmantk.rollpower");
        PlayerSettings.SetApplicationIdentifier(UnityEditor.Build.NamedBuildTarget.WebGL, "com.zizmantk.rollpower");
        PlayerSettings.runInBackground = true;
        PlayerSettings.visibleInBackground = true;

        // Windows
        PlayerSettings.fullScreenMode = FullScreenMode.Windowed;
        PlayerSettings.defaultScreenWidth = 1600;
        PlayerSettings.defaultScreenHeight = 900;
        PlayerSettings.resizableWindow = true;

        // WebGL for itch.io: gzip with a JS decompression fallback works whatever headers the host sends.
        PlayerSettings.defaultWebScreenWidth = 1280;
        PlayerSettings.defaultWebScreenHeight = 720;
        PlayerSettings.WebGL.compressionFormat = WebGLCompressionFormat.Gzip;
        PlayerSettings.WebGL.decompressionFallback = true;
        PlayerSettings.WebGL.dataCaching = true;
        PlayerSettings.WebGL.exceptionSupport = WebGLExceptionSupport.None;
        PlayerSettings.WebGL.template = "APPLICATION:Default";

        // App icon (generated by MakeItchAssets and copied into the project).
        const string iconPath = "Assets/Branding/Icon.png";
        var icon = AssetDatabase.LoadAssetAtPath<Texture2D>(iconPath);
        if (icon != null) PlayerSettings.SetIcons(UnityEditor.Build.NamedBuildTarget.Unknown, new[] { icon }, IconKind.Any);

        AddDPadAxes();
        AssetDatabase.SaveAssets();
        Debug.Log("[RollPower] player settings configured, version " + Version);
    }

    /// <summary>Adds DPadX / DPadY joystick axes (XInput axes 6 and 7) used by Controls.</summary>
    static void AddDPadAxes()
    {
        var asset = AssetDatabase.LoadAllAssetsAtPath("ProjectSettings/InputManager.asset")[0];
        var so = new SerializedObject(asset);
        var axes = so.FindProperty("m_Axes");
        void Add(string name, int axis)
        {
            for (int i = 0; i < axes.arraySize; i++)
                if (axes.GetArrayElementAtIndex(i).FindPropertyRelative("m_Name").stringValue == name) return;
            axes.arraySize++;
            var a = axes.GetArrayElementAtIndex(axes.arraySize - 1);
            a.FindPropertyRelative("m_Name").stringValue = name;
            a.FindPropertyRelative("descriptiveName").stringValue = "";
            a.FindPropertyRelative("descriptiveNegativeName").stringValue = "";
            a.FindPropertyRelative("negativeButton").stringValue = "";
            a.FindPropertyRelative("positiveButton").stringValue = "";
            a.FindPropertyRelative("altNegativeButton").stringValue = "";
            a.FindPropertyRelative("altPositiveButton").stringValue = "";
            a.FindPropertyRelative("gravity").floatValue = 0f;
            a.FindPropertyRelative("dead").floatValue = 0.2f;
            a.FindPropertyRelative("sensitivity").floatValue = 1f;
            a.FindPropertyRelative("snap").boolValue = false;
            a.FindPropertyRelative("invert").boolValue = false;
            a.FindPropertyRelative("type").intValue = 2; // joystick axis
            a.FindPropertyRelative("axis").intValue = axis;
            a.FindPropertyRelative("joyNum").intValue = 0;
        }
        Add("DPadX", 5);
        Add("DPadY", 6);
        so.ApplyModifiedProperties();
    }

    [MenuItem("Roll Power/Build Windows")]
    public static void BuildWindows() => Build(BuildTarget.StandaloneWindows64, GetArg("-buildOut") ?? "Builds/RollPower-Windows/RollPower.exe");

    [MenuItem("Roll Power/Build WebGL")]
    public static void BuildWebGL() => Build(BuildTarget.WebGL, GetArg("-buildOut") ?? "Builds/RollPower-WebGL");

    static void Build(BuildTarget target, string path)
    {
        ConfigurePlayer();
        var report = BuildPipeline.BuildPlayer(new BuildPlayerOptions
        {
            scenes = new[] { ScenePath },
            locationPathName = path,
            target = target,
            options = BuildOptions.None,
        });
        var s = report.summary;
        Debug.Log($"[RollPower] Build {target} {s.result}: {s.totalErrors} errors, {s.totalSize / (1024f * 1024f):0.0} MB, {s.totalTime.TotalSeconds:0}s -> {s.outputPath}");
        if (Application.isBatchMode && s.result != UnityEditor.Build.Reporting.BuildResult.Succeeded) EditorApplication.Exit(1);
    }

    /// <summary>Batch mode: builds the world in edit mode and renders the main camera to a PNG (-previewOut path).</summary>
    public static void Preview()
    {
        string outPath = GetArg("-previewOut") ?? Path.GetFullPath("preview.png");
        EditorSceneManager.OpenScene(ScenePath, OpenSceneMode.Single);
        var boot = UnityEngine.Object.FindAnyObjectByType<GameBootstrap>();
        boot.BuildWorld();
        RenderCamera(Camera.main, outPath, 1600, 900);
        Debug.Log("[RollPower] Preview written to " + outPath);
    }

    /// <summary>
    /// Batch mode: the autopilot plays the real wave game (upgrades picked automatically) for up to
    /// -playSeconds of game time (default 240), logging waves, bombs and the boss, and saving a frame
    /// every 2 seconds (-previewOut folder). Pass -godmode to keep the dice alive.
    /// </summary>
    public static void PlayTest()
    {
        string outDir = GetArg("-previewOut") ?? Path.GetFullPath("playtest");
        float seconds = float.TryParse(GetArg("-playSeconds"), out float ps) ? ps : 240f;
        EditorSceneManager.OpenScene(ScenePath, OpenSceneMode.Single);
        var boot = UnityEngine.Object.FindAnyObjectByType<GameBootstrap>();
        boot.BuildWorld();
        var loop = boot.Loop;
        var game = loop.Game;
        loop.AutoPickUpgrades = true;
        game.Invincible = Array.IndexOf(Environment.GetCommandLineArgs(), "-godmode") >= 0;
        var bot = new Autopilot(boot.Controller, loop.Weapons, game);
        var cam = Camera.main.GetComponent<CameraFollow>();
        int rolls = 0, shots = 0, lastWave = 0, frame = 0, bombs = 0;
        boot.Controller.TopChanged += (a, b) => rolls++;
        loop.Weapons.Fired += d => shots++;
        game.WaveCleared += w => Debug.Log($"[RollPower] {frame / 30f:0.0}s wave {w} cleared, hp {game.Hp}/{game.MaxHp}, score {game.Score}, bombs disposed {game.BombsDisposed}/{bombs}");

        const float dt = 1f / 30f;
        for (; frame < 30 * seconds && !game.Lost; frame++)
        {
            int before = game.Bombs.All.Count;
            bot.Step(dt);
            loop.Step(dt, true);
            if (game.Bombs.All.Count > before) bombs += game.Bombs.All.Count - before;
            if (game.Wave != lastWave)
            {
                lastWave = game.Wave;
                Debug.Log($"[RollPower] {frame / 30f:0.0}s wave {game.Wave} started{(game.BossWave ? " (BOSS)" : "")}, hp {game.Hp}");
            }
            if (frame % 60 == 0) Shot(cam, outDir, frame / 60);
        }
        Debug.Log($"[RollPower] PlayTest end after {frame / 30f:0}s: wave {game.Wave}, lost {game.Lost}, hp {game.Hp}, rolls {rolls}, shots {shots}, " +
                  $"kills {game.Kills}, bombs {bombs} (disposed {game.BombsDisposed}), best combo x{game.BestCombo}, score {game.Score}");
    }

    /// <summary>
    /// Batch mode, art-direction prototypes (-theme N): plays 16 s with the autopilot and saves gameplay frames,
    /// then a close-up of the die and a lineup of the six guns (-previewOut folder, 1920x1080).
    /// </summary>
    public static void ArtShots()
    {
        string outDir = GetArg("-previewOut") ?? Path.GetFullPath("artshots");
        EditorSceneManager.OpenScene(ScenePath, OpenSceneMode.Single);
        var boot = UnityEngine.Object.FindAnyObjectByType<GameBootstrap>();
        boot.BuildWorld();
        var loop = boot.Loop;
        loop.AutoPickUpgrades = true;
        loop.Game.Invincible = true;
        var bot = new Autopilot(boot.Controller, loop.Weapons, loop.Game);
        var cam = Camera.main.GetComponent<CameraFollow>();
        const float dt = 1f / 30f;
        for (int frame = 0; frame <= 30 * 16; frame++)
        {
            bot.Step(dt);
            loop.Step(dt, true);
            if (frame > 0 && frame % 60 == 0) { cam.SnapToTarget(); RenderCamera(cam.GetComponent<Camera>(), Path.Combine(outDir, $"play{frame / 60:00}.png"), 1920, 1080); }
        }

        // Die close-up, three-quarter view from the front-right.
        var c = Camera.main;
        var diePos = boot.Dice.Root.position + Vector3.up * 0.8f;
        cam.enabled = false;
        float fov = c.fieldOfView;
        c.fieldOfView = 30f;
        c.transform.position = diePos + new Vector3(2.6f, 2.2f, -3.4f);
        c.transform.LookAt(diePos);
        RenderCamera(c, Path.Combine(outDir, "die.png"), 1920, 1080);

        // Gun lineup on a dark plinth, away from the arena.
        var line = new GameObject("GunLineup").transform;
        line.position = new Vector3(0f, 0f, -60f);
        var plinth = boot.Palette.Get("LineupPlinth", Art.Theme == 1 ? new Color(0.42f, 0.45f, 0.5f) : Art.Theme == 3 ? new Color(0.1f, 0.2f, 0.31f) : new Color(0.08f, 0.09f, 0.11f), 0.6f, 0.3f);
        Prim.Make(PrimitiveType.Cube, "Plinth", line, new Vector3(0f, -0.3f, 0f), new Vector3(9f, 0.2f, 2.2f), plinth);
        for (int n = 1; n <= 6; n++)
        {
            var g = GunModels.Build(n, boot.Palette, line, new System.Collections.Generic.List<Transform>());
            g.localPosition = new Vector3((n - 3.5f) * 1.45f, 0f, 0f);
            g.localRotation = Quaternion.Euler(0f, 145f, 0f);
            g.localScale *= 1.25f;
        }
        var key = new GameObject("LineupLight").AddComponent<Light>();
        key.type = LightType.Point; key.range = 12f; key.intensity = 3f; key.color = Color.white;
        key.transform.position = line.position + new Vector3(-2f, 4f, -3f);
        c.fieldOfView = 28f;
        c.transform.position = line.position + new Vector3(0f, 4.2f, -9.5f);
        c.transform.LookAt(line.position + Vector3.up * 0.1f);
        RenderCamera(c, Path.Combine(outDir, "guns.png"), 1920, 1080);
        // Same lineup seen from the gameplay camera angle (silhouettes as the player sees them).
        c.fieldOfView = 30f;
        c.transform.position = line.position + new Vector3(0f, 7.6f, -6.2f);
        c.transform.LookAt(line.position);
        RenderCamera(c, Path.Combine(outDir, "guns_top.png"), 1920, 1080);

        if (Art.Theme == 3)
        {
            // Obstacle close-up: barrier (roll 1) and conduit (roll 2) on a strip of deck.
            var props = new GameObject("PropLineup").transform;
            props.position = new Vector3(0f, 0f, -90f);
            Prim.Make(PrimitiveType.Cube, "Deck", props, new Vector3(0f, -0.15f, 0f), new Vector3(9f, 0.3f, 5f), boot.Palette.Get("T3DeckA", Color.black));
            var b = new GameObject("Barrier").transform; b.SetParent(props, false); b.localPosition = new Vector3(-2.2f, 0f, 0f);
            NavyProps.Barrier(boot.Palette, b);
            var cd = new GameObject("Conduit").transform; cd.SetParent(props, false); cd.localPosition = new Vector3(1.2f, 0f, 0.3f);
            NavyProps.Conduit(boot.Palette, cd, true);
            var pl = new GameObject("PropLight").AddComponent<Light>();
            pl.type = LightType.Point; pl.range = 12f; pl.intensity = 3f; pl.color = Color.white;
            pl.transform.position = props.position + new Vector3(-2f, 4f, -3f);
            c.fieldOfView = 30f;
            c.transform.position = props.position + new Vector3(0f, 4.2f, -6.4f);
            c.transform.LookAt(props.position + Vector3.up * 0.2f);
            RenderCamera(c, Path.Combine(outDir, "props.png"), 1920, 1080);
        }

        // Enemy lineup: crawler, drone, tank, mite, bomber on a strip of deck.
        {
            var en = new GameObject("EnemyLineup").transform;
            en.position = new Vector3(0f, 0f, -120f);
            Prim.Make(PrimitiveType.Cube, "Deck", en, new Vector3(0f, -0.15f, 0f), new Vector3(11f, 0.3f, 5f), Art.Theme == 3 ? boot.Palette.Get("T3DeckA", Color.black) : plinth);
            var kinds = new[] { EnemyKind.Crawler, EnemyKind.Drone, EnemyKind.Tank, EnemyKind.Mite, EnemyKind.Bomber };
            for (int i = 0; i < kinds.Length; i++)
            {
                var x = (i - 2) * 2f;
                var en1 = EnemyModels.Create(kinds[i], boot.Palette, en.position + new Vector3(x, 0f, 0f));
                en1.t.localScale = Vector3.one * (kinds[i] == EnemyKind.Mite ? 1.6f : 1f);
                en1.t.rotation = Quaternion.Euler(0f, 200f, 0f);
                if (kinds[i] == EnemyKind.Drone) en1.t.position += Vector3.down * 1.4f;
            }
            var el = new GameObject("EnemyLight").AddComponent<Light>();
            el.type = LightType.Point; el.range = 14f; el.intensity = 3f; el.color = Color.white;
            el.transform.position = en.position + new Vector3(-2f, 5f, -4f);
            c.fieldOfView = 30f;
            c.transform.position = en.position + new Vector3(0f, 4.6f, -9f);
            c.transform.LookAt(en.position + Vector3.up * 0.5f);
            RenderCamera(c, Path.Combine(outDir, "enemies.png"), 1920, 1080);
            c.transform.position = en.position + new Vector3(0f, 9.5f, -7.6f);
            c.transform.LookAt(en.position);
            RenderCamera(c, Path.Combine(outDir, "enemies_top.png"), 1920, 1080);
        }
        c.fieldOfView = fov;
        Debug.Log("[RollPower] ArtShots theme " + Art.Theme + " -> " + outDir);
    }

    static void Shot(CameraFollow cam, string dir, int frame)
    {
        cam.SnapToTarget();
        int w = int.TryParse(GetArg("-shotWidth"), out int sw) ? sw : 640; // -shotWidth 1920 for mock-up backgrounds
        RenderCamera(cam.GetComponent<Camera>(), Path.Combine(dir, $"f{frame:000}.png"), w, w * 9 / 16);
    }

    /// <summary>Batch mode: synthesizes all sounds + music and writes them as WAV files (-previewOut folder).</summary>
    public static void ExportSounds()
    {
        string dir = GetArg("-previewOut") ?? Path.GetFullPath("Audio");
        Debug.Log("[RollPower] " + Sound.ExportWavs(dir).Replace("\n", "\n[RollPower] "));
    }

    /// <summary>Debug: renders red/green/blue lit and glowing spheres and logs their material state.</summary>
    public static void ColorTest()
    {
        string outPath = GetArg("-previewOut") ?? Path.GetFullPath("colortest.png");
        EditorSceneManager.OpenScene(ScenePath, OpenSceneMode.Single);
        var boot = UnityEngine.Object.FindAnyObjectByType<GameBootstrap>();
        var pal = new Palette(boot.baseMaterial, boot.glowMaterial);
        var cam = Camera.main;
        cam.transform.position = new Vector3(0f, 1f, -6f);
        cam.transform.rotation = Quaternion.identity;
        new GameObject("L").AddComponent<Light>().type = LightType.Directional;
        Color[] cols = { Color.red, Color.green, Color.blue };
        for (int i = 0; i < 3; i++)
        {
            var lit = pal.Get("T" + i, cols[i], 0.5f);
            var glow = pal.Glow("G" + i, cols[i], 3f);
            Prim.Make(PrimitiveType.Sphere, "Lit" + i, null, new Vector3(-2f + i * 2f, 2f, 0f), Vector3.one, lit);
            Prim.Make(PrimitiveType.Sphere, "Glow" + i, null, new Vector3(-2f + i * 2f, 0f, 0f), Vector3.one, glow);
            Debug.Log($"[RollPower] {glow.name}: shader {glow.shader.name}, kw [{string.Join(",", glow.shaderKeywords)}], emission {glow.GetColor("_EmissionColor")}, base {glow.GetColor("_BaseColor")}");
        }
        Debug.Log($"[RollPower] pipeline: {UnityEngine.Rendering.GraphicsSettings.currentRenderPipeline?.name}, cam type {cam.GetType()}");
        RenderCamera(cam, outPath, 800, 450);
    }

    public static void RenderCamera(Camera cam, string path, int w, int h)
    {
        ShaderUtil.allowAsyncCompilation = false; // render real shaders, not async-compile placeholders
        var rt = new RenderTexture(w, h, 24, RenderTextureFormat.ARGB32) { antiAliasing = 8 };
        var request = new UnityEngine.Rendering.RenderPipeline.StandardRequest { destination = rt };
        if (UnityEngine.Rendering.RenderPipeline.SupportsRenderRequest(cam, request))
            UnityEngine.Rendering.RenderPipeline.SubmitRenderRequest(cam, request);
        else
        {
            cam.targetTexture = rt;
            cam.Render();
        }
        RenderTexture.active = rt;
        var tex = new Texture2D(w, h, TextureFormat.RGB24, false);
        tex.ReadPixels(new Rect(0, 0, w, h), 0, 0);
        tex.Apply();
        cam.targetTexture = null;
        RenderTexture.active = null;
        Directory.CreateDirectory(Path.GetDirectoryName(path));
        File.WriteAllBytes(path, tex.EncodeToPNG());
        UnityEngine.Object.DestroyImmediate(rt);
        UnityEngine.Object.DestroyImmediate(tex);
    }

    /// <summary>
    /// Batch mode test of the roll guide. For each problem enemy (drones, tanks, the boss) and each of the
    /// six starting faces: if the current gun can't hurt the enemies, the guide must suggest a roll; the dice
    /// then follows it (line up, dash, slam) and must land on the suggested face with a gun that hurts them.
    /// Exits with code 1 if any case fails.
    /// </summary>
    public static void TestRollGuide()
    {
        EditorSceneManager.OpenScene(ScenePath, OpenSceneMode.Single);
        int pass = 0, fail = 0, skipped = 0;
        const float dt = 1f / 60f;
        foreach (var kind in new[] { EnemyKind.Drone, EnemyKind.Tank, EnemyKind.Boss })
        for (int start = 1; start <= 6; start++)
        {
            var boot = UnityEngine.Object.FindAnyObjectByType<GameBootstrap>();
            boot.BuildWorld();
            var loop = boot.Loop;
            var game = loop.Game;
            var dice = boot.Controller;
            game.ManualSpawning = true;
            game.Invincible = true;
            dice.InputOverride = Vector2.zero;
            dice.ForceTop(start);

            if (kind == EnemyKind.Boss)
            {
                var b = game.Spawn(EnemyKind.Boss, new Vector3(0f, 0f, 6f));
                b.boss.rest = 999f; // keep its number fixed during the test
            }
            else for (int i = 0; i < 3; i++) game.Spawn(kind, new Vector3(-6f + i * 6f, 0f, 8.5f));

            loop.Step(dt, false);
            var gun = WeaponDef.All[dice.TopNumber];
            string label = $"{kind,-6} start {start} ({gun.name})";
            if (game.Immune(gun) == null)
            {
                if (loop.Guide.Plan != null) { fail++; Debug.LogError($"[RollPower] FAIL {label}: guide shown although the gun already works"); }
                else { skipped++; Debug.Log($"[RollPower] ok   {label}: gun already works, no guide"); }
                continue;
            }
            var plan = loop.Guide.Plan;
            if (plan == null) { fail++; Debug.LogError($"[RollPower] FAIL {label}: wrong gun but no guide"); continue; }
            string advice = $"ROLL {RollAdvisor.Arrow(plan.dir)} FOR {plan.Gun.name} via {plan.obstacle.kind}";

            // Follow the advice like a player would: line up behind the marked obstacle and dash into it.
            dice.Teleport(plan.approach);
            dice.InputOverride = new Vector2(plan.dir.x, plan.dir.z);
            int landed = -1;
            System.Action<int, int> onRoll = (o, n) => { if (landed < 0) landed = n; };
            dice.TopChanged += onRoll;
            for (int f = 0; f < 180 && landed < 0; f++)
            {
                if (f == 2) dice.Dash();
                loop.Step(dt, false);
            }
            dice.TopChanged -= onRoll;
            bool hurts = landed > 0 && game.Immune(WeaponDef.All[landed]) == null;
            if (landed == plan.top && hurts) { pass++; Debug.Log($"[RollPower] PASS {label}: {advice} -> landed {landed}"); }
            else { fail++; Debug.LogError($"[RollPower] FAIL {label}: {advice} -> landed {landed}, gun hurts enemies: {hurts}"); }
        }
        Debug.Log($"[RollPower] TestRollGuide: {pass} passed, {fail} failed, {skipped} cases where the gun already worked");
        if (Application.isBatchMode) EditorApplication.Exit(fail > 0 ? 1 : 0);
    }

    /// <summary>
    /// Batch mode: turns in-player captures (-assetsIn folder, from RollPower.exe -capture) into itch.io page
    /// assets in -assetsOut: cover.png (630x500 from the *_cover shot), icon.png (512x512) and 1920x1080 screenshots.
    /// </summary>
    public static void MakeItchAssets()
    {
        string src = GetArg("-assetsIn"), dst = GetArg("-assetsOut") ?? "Builds/itch";
        Directory.CreateDirectory(Path.Combine(dst, "screenshots"));
        foreach (var file in Directory.GetFiles(src, "*.png"))
        {
            var tex = new Texture2D(2, 2);
            tex.LoadImage(File.ReadAllBytes(file));
            string name = Path.GetFileNameWithoutExtension(file);
            if (name.EndsWith("_cover"))
            {
                // Centre crop to the 630:500 cover aspect, then scale.
                float aspect = 630f / 500f;
                int ch = tex.height, cw = Mathf.RoundToInt(ch * aspect);
                SavePng(Resample(tex, new Rect((tex.width - cw) * 0.5f, 0, cw, ch), 630, 500), Path.Combine(dst, "cover.png"));
            }
            else SavePng(Resample(tex, new Rect(0, 0, tex.width, tex.height), 1920, 1080), Path.Combine(dst, "screenshots", name + ".png"));
            UnityEngine.Object.DestroyImmediate(tex);
        }
        SavePng(DrawIcon(512), Path.Combine(dst, "icon.png"));
        Debug.Log("[RollPower] itch assets written to " + Path.GetFullPath(dst));
    }

    /// <summary>App icon: the gold hero die showing a five, with a darker rim and a soft top highlight.</summary>
    static Texture2D DrawIcon(int size)
    {
        var tex = new Texture2D(size, size, TextureFormat.RGBA32, false);
        Color gold = UiKit.Gold, rim = UiKit.GoldDeep, ink = UiKit.Ink;
        float h = size * 0.5f, radius = size * 0.2f, half = size * 0.46f, border = size * 0.035f;
        Vector2[] pips = { new Vector2(-1, -1), new Vector2(1, -1), Vector2.zero, new Vector2(-1, 1), new Vector2(1, 1) };
        for (int y = 0; y < size; y++)
        for (int x = 0; x < size; x++)
        {
            Vector2 p = new Vector2(x + 0.5f - h, y + 0.5f - h);
            // Signed distance to a rounded square (negative inside).
            Vector2 q = new Vector2(Mathf.Abs(p.x), Mathf.Abs(p.y)) - Vector2.one * (half - radius);
            float d = new Vector2(Mathf.Max(q.x, 0f), Mathf.Max(q.y, 0f)).magnitude + Mathf.Min(Mathf.Max(q.x, q.y), 0f) - radius;
            float cover = Mathf.Clamp01(0.5f - d);
            Color c = Color.Lerp(gold, rim, Mathf.Clamp01((d + border) / 1.5f + 0.5f));
            c = Color.Lerp(c, Color.white, Mathf.Clamp01(p.y / size) * 0.25f); // lighter towards the top
            foreach (var pip in pips)
            {
                float pd = (p - pip * size * 0.22f).magnitude - size * 0.085f;
                c = Color.Lerp(c, ink, Mathf.Clamp01(0.5f - pd));
            }
            c.a = cover;
            tex.SetPixel(x, y, c);
        }
        tex.Apply();
        return tex;
    }

    /// <summary>Crops 'src' (pixel rect, origin bottom-left) and scales it to w x h on the GPU.</summary>
    static Texture2D Resample(Texture2D src, Rect crop, int w, int h)
    {
        var rt = RenderTexture.GetTemporary(w, h, 0, RenderTextureFormat.ARGB32, RenderTextureReadWrite.sRGB);
        src.filterMode = FilterMode.Bilinear;
        var scale = new Vector2(crop.width / src.width, crop.height / src.height);
        var offset = new Vector2(crop.x / src.width, crop.y / src.height);
        Graphics.Blit(src, rt, scale, offset);
        var prev = RenderTexture.active;
        RenderTexture.active = rt;
        var outTex = new Texture2D(w, h, TextureFormat.RGB24, false);
        outTex.ReadPixels(new Rect(0, 0, w, h), 0, 0);
        outTex.Apply();
        RenderTexture.active = prev;
        RenderTexture.ReleaseTemporary(rt);
        return outTex;
    }

    static void SavePng(Texture2D tex, string path)
    {
        File.WriteAllBytes(path, tex.EncodeToPNG());
        UnityEngine.Object.DestroyImmediate(tex);
    }

    static string GetArg(string name)
    {
        var args = Environment.GetCommandLineArgs();
        for (int i = 0; i < args.Length - 1; i++)
            if (args[i] == name) return args[i + 1];
        return null;
    }
}
